apiVersion: v2
name: go-server
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.23.0"
maintainers:
- name: "Vadim SkinonikS.#"
  url: "https://github.com/SkinonikS"
