apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "postgres.fullname" . | quote }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.instancesCount }}
  walStorage:
    {{- toYaml .Values.walStorage | nindent 4 }}
  storage:
    {{- toYaml .Values.storage | nindent 4 }}