{{- if and .Values.bootstrap.initdb .Values.bootstrap.initdb.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bootstrap.initdb.secret.name | quote }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.bootstrap.initdb.owner | b64enc | quote }}
  password: {{ .Values.bootstrap.initdb.secret.password | b64enc | quote }}
{{- end }}