apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "postgres.fullname" . | quote }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.instancesCount }}
  {{- if .Values.walStorage }}
  walStorage:
    {{- toYaml .Values.walStorage | nindent 4 }}
  {{- end }}
  storage:
    {{- toYaml .Values.storage | nindent 4 }}
  bootstrap:
    {{- if .Values.bootstrap.initdb }}
    initdb:
      database: {{ .Values.bootstrap.initdb.database | quote }}
      owner: {{ .Values.bootstrap.initdb.owner | quote }}
      {{- if .Values.bootstrap.initdb.secret }}
      secret:
        name: {{ .Values.bootstrap.initdb.secret.name | quote }}
      {{- end }}
      {{- if .Values.bootstrap.initdb.extensions }}
      postInitTemplateSQLRefs:
        configMapRefs:
          - name: post-init-template-sql
            key: extensions.sql
      {{- end }}
      {{- if .Values.bootstrap.initdb.filePath }}
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: post-init-app-sql
            key: init.sql
      {{- end }}
    {{- end }}