apiVersion: v1
kind: Service
metadata:
  name: {{ include "go.fullname" . | quote }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
spec:
  ports:
  - name: "http"
    protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: "http"
  selector:
    {{- include "go.selectorLabels" . | nindent 4 }}
