name: Build WPF (.NET Framework)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore frontend/GW_UI/GW_UI.sln

      - name: Build solution
        run: msbuild frontend/GW_UI/GW_UI.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: |
            **/bin/Release
