name: Build WPF (.NET Framework)

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore frontend/GW_UI/GW_UI.sln

      - name: Build solution (Release|Any CPU)
        run: msbuild frontend/GW_UI/GW_UI.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: '**/bin/Release'
          asset_name: "GW_UI_Release.zip"
          asset_content_type: application/zip
